<a href="https://colab.research.google.com/github/berggama/bootcamp_embraer/blob/main/trabalho_pratico_modulo_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Trabalho Prático
## Módulo 2 - Python para a análise de dados

### Objetivos 
Exercitar os seguintes conceitos trabalhados no Módulo:
- Criação e manipulação de numpy arrays.
- Leitura de dados e manipulação de DataFrames e Series no pandas.
- Fundamentos de aprendizado de máquinas.

### Enunciado
Em um ambiente de desenvolvimento em Python (recomenda-se o Google
Colaboratory), execute e/ou complete os trechos de código contidos nas
imagens.

### Atividades

1) Acessar o ambiente Google Colaboratory (recomendado) ou qualquer ambiente de desenvolvimento em Python.

2) Importar as bibliotecas do numpy e pandas, conforme:
```
import numpy as np
import pandas as pd
```

In [1]:
import numpy as np
import pandas as pd

3) Executar/Completar os trechos de código a seguir para responder às questões objetivas. Complete-os de forma que o resultado da execução da função print seja igual ao da imagem correspondente. Após isso, responder as perguntas do teste na nossa plataforma. Cada código escrito abaixo, ajudará-lo a responder as questões.

```
#== CÓDIGO 1 == #
Z = np.zeros((4,))
print("Z:", Z) 
```

In [2]:
# == CÓDIGO 1 == #
Z = np.zeros((4,))
print("Z:", Z) 

Z: [0. 0. 0. 0.]


```
#== CÓDIGO 2 == #
Z = np.zeros((4,))
Z[1] = 1.
print("Z:", Z) 
```

In [3]:
# == CÓDIGO 2 == #
Z = np.zeros((4,))
Z[1] = 1.
print("Z:", Z) 

Z: [0. 1. 0. 0.]


```
#== CÓDIGO 3 == #
Z = np.zeros((4,))
Z[1:] = 1.
print("Z:", Z) 
```

In [4]:
# == CÓDIGO 3 == #
Z = np.zeros((4,))
Z[1:] = 1.
print("Z:", Z) 

Z: [0. 1. 1. 1.]


```
#== CÓDIGO 4 == #
Z = # complete o código
# complete o código
print("Z:", Z) 
```
Output:
```
Z:[1. 1. 1. 0.]
```

In [8]:
# == CÓDIGO 4 == #
Z = np.ones(4,)
Z[-1] = 0.
print("Z:", Z)

Z: [1. 1. 1. 0.]


```
#== CÓDIGO 5 == #
X = # complete o código
print("X:\n", X) 
```
Output:
```
X:
  [[2. 2.]
  [2. 2.]]
```

In [12]:
# == CÓDIGO 5 == #
X = np.ones([2,2])*2
print("X:\n", X) 

X:
 [[2. 2.]
 [2. 2.]]


```
#== CÓDIGO 6 == #
X = np.array([[1, 2], [3, 4]])
Y = X[0, :]
Y[1] = 10
print("X:\n", X) 
```

In [13]:
# == CÓDIGO 6 == #
X = np.array([[1, 2], [3, 4]])
Y = X[0, :]
Y[1] = 10
print("X:\n", X) 

X:
 [[ 1 10]
 [ 3  4]]


```
#== CÓDIGO 7 == #
X = np.array([[1, 3], [11, 10]])
print(np.mean(X[X > np.pi])) 
```

In [14]:
# == CÓDIGO 7 == #
X = np.array([[1, 3], [11, 10]])
print(np.mean(X[X > np.pi])) 

10.5


```
#== CÓDIGO 8 == #
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 
                    'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no',
                     'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']
```

In [24]:
#== CÓDIGO 8 == #
data = {'animal': ['cat', 'cat', 'snake', 'dog', 'dog', 
                    'cat', 'snake', 'cat', 'dog', 'dog'],
        'age': [2.5, 3, 0.5, np.nan, 5, 2, 4.5, np.nan, 7, 3],
        'visits': [1, 3, 2, 3, 2, 3, 1, 1, 2, 1],
        'priority': ['yes', 'yes', 'no', 'yes', 'no',
                     'no', 'no', 'yes', 'no', 'no']}

labels = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j']

```
# == CÓDIGO 9 == #
df = pd.DataFrame(data=data, index=labels)
```

In [16]:
# == CÓDIGO 9 == #
df = pd.DataFrame(data=data, index=labels)

```
# == CÓDIGO 10 == #
y_true = np.array([1., 2., 1.])
y_pred = np.array([1.1, 1.98, 1.05])
```

In [51]:
# == CÓDIGO 10 == #
y_true = np.array([1., 2., 1.])
y_pred = np.array([1.1, 1.98, 1.05])